functional:
  - требование 3
  - требование 4
  - требование 8
  - требование 9
non-functional:
  - требование 1
  - требование 2
  - требование 5
  - требование 6
  - требование 7
  - требоване 10  
implicit:
  - Оформленный товар должен исчезать из корзины
  - Пользователь должен иметь возможность отслеживать товар
  - Пользователь должен иметь возможность менять количество товара в корзине
  - Пользователь должен иметь воможность удалять товар из корзины
  - При нажатие "Previous" или "Next" в конце списка, новая страница должна показывать перечень товаров с начала списка.
