functional:
   - требование 1
   - требование 2
   - требование 3
   - требование 4
   - требование 8
   - требование 9
non-functional:
   - требование 5
   - требование 6
   - требоване 10
implicit:
   - Сайт должен быть способен обрабатывать большое количество трафика.
